spring:
  application:
    name: hotel-app-ns
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hotel_app_fponce
    hikari:
      minIdle: 10
      idle-timeout: 10000
      maximumPoolSize: 30
server:
  port: 18080
  servlet:
    context-path: /api/hotelapp
