spring:
  application:
    name: hotel-app-ns
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hotel_app_fponce
server:
  port: 8080
  servlet:
    context-path: /api
